version: '3.8'
# volumes:
#   user_service_postgres_data: {}
#   product_service_postgres_data: {}
#   order_service_postgres_data: {}
#   notification_service_postgres_data: {}

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - product_service
      - order_service
      - notification_service

  user_service:
    build: ./user_service
    ports:
      - "8001:8001"
    # depends_on:
    #   - user_db

  product_service:
    build: ./production_service
    ports:
      - "8002:8002"
    # depends_on:
    #   - product_db

  order_service:
    build: ./order_service
    ports:
      - "8003:8003"
    # depends_on:
    #   - order_db

  notification_service:
    build: ./notification_service
    ports:
      - "8004:8004"
    # depends_on:
    #   - notification_db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    ports:
      - "6379:6379"

  # user_db:
  #   image: postgres
  #   volumes:
  #     - user_service_postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER: postgres
  #     - POSTGRES_PASSWORD: postgres
  #     - POSTGRES_DB: postgres
  
  # product_db:
  #   image: postgres
  #   volumes:
  #     - product_service_postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER: postgres
  #     - POSTGRES_PASSWORD: postgres
  #     - POSTGRES_DB: postgres

  # order_db:
  #   image: postgres
  #   volumes:
  #     - order_service_postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER: postgres
  #     - POSTGRES_PASSWORD: postgres
  #     - POSTGRES_DB: postgres

  # notification_db:
  #   image: postgres
  #   volumes:
  #     - notification_service_postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER: postgres
  #     - POSTGRES_PASSWORD: postgres
  #     - POSTGRES_DB: postgres